pipeline{
    agent any
    stages{
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Verify Package') {
            steps {
                sh 'ls -l target/'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                    echo 'Test Completed!!'
                }
            }
        }
    }
}
